[package]
name = "scan-duplicates"
version = "0.1.0"
authors = ["sardonicism-04 <110789901+sardonicism-04@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "0.23.14"
structopt = "0.3.21"
shellexpand = "2.1.0"
